name: Build and Deploy React App

# 1. Configuración del Disparador (Trigger)
# Esto ejecuta el pipeline en cada 'push' a la rama 'main'
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Descarga el código de tu repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # Paso 2: Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.21.0'

      # Paso 3: Instalar dependencias y Construir el proyecto
      - name: Install and Build
        run: |
          npm install
          npm run build

      # Paso 4: Copiar los archivos a la VM
      - name: Deploy to VM using SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_AWS }}
          username: ${{ secrets.SSH_USER_AWS }}
          key: ${{ secrets.SSH_PRIVATE_KEY_AWS }}
          port: 22
          source: "dist/" # La carpeta que se construye
          target: "/var/www/html/" # El destino
          strip_components: 1 # Para que no copie la carpeta 'build' sino su contenido

      # Paso 5: Reiniciar Nginx (Opcional, si es necesario)
      # - name: Restart Nginx
      #   uses: appleboy/ssh-action@v1.0.1
      #   with:
      #     host: ${{ secrets.SSH_HOST_AWS }}
      #     username: ${{ secrets.SSH_USER_AWS }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY_AWS }}
      #     port: 22
      #     script: |
      #       sudo systemctl restart nginx